### ISSUE TITLE
$CGI::POST_MAX does not validate POST on CGI v.4.40

### ISSUE THREAD

**Issue by arseniigorkin** [leejo/CGI.pm#233] opened 2019-03-14 19:49 UTC
I spent a lo of hours trying to make $CGI::POST_MAX working in the script I am writing.

I read a lot of docs and examples and all of them does not work for my case.

Firstly let's start off the example code below:

```
#!/usr/bin/perl

use strict;
use warnings;

use CGI qw/:standard cookie/;
$CGI::POST_MAX= 1024 * 1024 * 2;  # max 2MB
$CGI::DISABLE_UPLOADS = 1; # no uploads
use CGI::Carp qw(fatalsToBrowser);

my $q = CGI->new();

print "Content-type:text/html\n\n";
print "ERROR: $q->cgi_error()";
exit 0;
```
I need (and it is clearly seen from the example above) to prevent loading any data more than 2MB via POST request and raise a simple standard error (all is accurately according to the documentation to CGI.pm 4.40).

But this does not work. Whether I move calls of `$CGI::POST_MAX= 1024 * 1024 * 2;` and `$CGI::DISABLE_UPLOADS = 1;` all around my complete code, whether I change any values for them - nothing. The script passes any data (3, 4 and more MB).

If I check the field like in the documentation to the CGI.pm:

> This error message is actually defined by the HTTP protocol, and is designed to be returned to the browser as the CGI script's status code. For example:
```
 my $uploaded_file = $q->param('upload');
 if ( !$uploaded_file && $q->cgi_error() ) {
     print $q->header( -status => $q->cgi_error() );
     exit 0;
}

```
>  An attempt to send a POST larger than $POST_MAX bytes will cause param() to return an empty CGI parameter list.

the field holds a valid filename and nothing is going to be like described (all fields must be empty while exceeding maximum limits).

I use the latest Perl v.5.26.1 on Ubuntu 18.04. CGI.pm is v.4.40, Apache 2.4.29.

If you know how to make it work I will be thankful for your help!

**Comment by leejo** [comment] 2019-03-15 09:48
Looking at the CGI.pm code it would appear that the `Content-Length` header is checked against the value of `$CGI::POST_MAX` - can you confirm that the `Content-Length` header is being correctly set by the User-Agent and/or webserver that passes the request to the backend?

I do note that there is no test coverage for this in the distribution, so having a test case for this would be a useful addition.

**Comment by arseniigorkin** [comment] 2019-03-15 16:01
Dear Lee, it is very pleasant to speak to you!
Yes, headers 100% are set properly.
May I ask you if CGI.pm checks only headers, or it counts bytes of the uploaded data?
Because, headers can be cheated, as you know.
I currently use Apache limits for this sake, but it would be great to get back to CGI.pm on this.

I am not able to give a proper example at the moment. I will be happy to try later for you.
Thank you!

**Comment by leejo** [comment] 2019-03-15 17:08
@arseniigorkin - the implementation in CGI.pm is very simple: https://github.com/leejo/CGI.pm/blob/master/lib/CGI.pm#L532-L546

It doesn't count bytes as I guess that's a catch-22 situation - the file would have to be uploaded for us to be able to count the bytes, which sort of defeats some of the point of the `$CGI::POST_MAX` implementation.

If the headers are set correctly then perhaps this is a bug in the code. If you could reduce this to a simple test case (see some of the existing tests in the `t/` directory in this repo) then we can look into it further.

**Comment by leejo** [comment] 2019-03-25 19:48
@arseniigorkin - any progress on this?

**Comment by arseniigorkin** [comment] 2019-03-26 08:45
Dear Lee,

I think the problem is going from the place of using a few other modules in the code, which enable in themselves the CGI.pm. So, the other words:

```
use CGI.
use someModule

#code code code
.....
```

And the someModule uses CGI as well in it.
May it be a problem?

Thanks.

**Comment by leejo** [comment] 2019-03-26 08:52
Not sure. The upload size is controlled by a package variable, which you (or any other code) can freely modify as and when required. Like I say - if you can reduce this to a test case I can look into it, but otherwise it's just speculation as to what the problem is and I can't do anything to fix that.

**Comment by arseniigorkin** [comment] 2019-03-26 09:20
Dear Lee, thank you for your reply.
I will try to cut out some time to do it for you, but now it is a very hot time here and I really cannot dispose any of it for the test code creating.

I will try.

Thank you!

**Comment by leejo** [comment] 2019-04-27 14:19
@arseniigorkin - I'm going to close this for now. Please reopen another issue if this does look like a genuine problem with the distribution. Thanks!

**Closed by leejo** 2019-04-27 14:19 UTC
