### ISSUE TITLE
Cannot see all files submitted via file input with multiple on and files have the same name

### ISSUE THREAD

**Issue by ekangas1** [leejo/CGI.pm#191] opened 2015-12-15 16:12 UTC
Scenario:

1. Basic web form with:

<input type=file multiple name=files>

2. Open form in iOS and select multiple pictures

3. iOS attaches all images using the SAME name "image.jpg".

4. CGI.pm v4.x only sees ONE of these uploaded files.  Presumably they are collapsing via some hash internally.

Further investigation:

* Uploading multiple files from Chrome, for example, works fine.
* Uploading an image and a movie from iOS works fine, as iOS attaches them using different file names in the same multiple upload
* CGI.pm v3.x does NOT have this issue -- servers with v3.x installed see all uploaded files even if they all have the same name.

This should be very easy to reproduce and fix.

**Comment by leejo** [comment] 2015-12-15 16:33
Can you provide the simple web form so i can turn this into a test please.

**Comment by ekangas1** [comment] 2015-12-15 16:43
http://erikkangas.com/test/cgi_191.html

~~~~

<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>

<form name=FORM_NAME method=POST enctype='multipart/form-data'
   action="https://beta.luxsci.com/perl/post/500-3823-zUXd">

<p>Multiple files: <input multiple type=file name=file_name></p>

<p><input type=submit value="Upload files"></p>

</form>
</body>
</html>

**Comment by leejo** [comment] 2015-12-15 17:13
I just added a test for duplicate filename (and name) values in multipart upload data in ab0c515 and it works on every commit back to the v3.x releases so i'm not sure what the problem is here. Can you provide an example of the upload data that is being sent to your script?

**Comment by ekangas1** [comment] 2015-12-15 18:23
I made a bunch of updates here ... but they seem gone.

Anyway, I have figured out the issue.  Using "upload" works fine.  I have neen using the ".tmpfiles" internal to get all temp files and their details (content type, file name, etc) without needing to open file handles, etc.  I can also use this to get all uploaded files without needing to know ahead of time what the file upload field names are.... which is very useful.

In the case of file+multiple and duplicate file names, the ".tmpfiles" hash does not include all of the actual temporary files ... and thus I was missing them.

I have updated my code to 1st iterate over ".tmpfiles" to get all the content types and such.  Then to use "upload" to open file handles and get arrays of them for fields that have a NULL in the values (indicating a multiple upload) ... then pulling the file names and temp paths out of those file handles.

So -- you can close this bug.

My suggestion is only to allow ".tmpfiles" to contain hash keys for ALL temporary files as it does in other cases and as does in v3.x of CGI.

Thank you!

**Comment by leejo** [comment] 2015-12-15 18:48
Your comments are on the commit, here's my reply: https://github.com/leejo/CGI.pm/commit/ab0c5157ae0c18237dea56ba7dca7974c793aaeb#commitcomment-14993923

I'm closing this as you shouldn't be accessing the `.tmpfiles` variables as it's internal to the package and private (as is any hash key prefixed with a `.`, none of these are documented and should not really be accessed externally as they may well change). There are ways to get the information about the file content type and such without accessing the private hash key, as per the docs:

```perl
           my $filehandle = $q->upload( 'uploaded_file' );
           my $type       = $q->uploadInfo( $filehandle )->{'Content-Type'};
           if ( $type ne 'text/html' ) {
               die "HTML FILES ONLY!";
           }
```

**Closed by leejo** 2015-12-15 18:48 UTC

**Comment by leejo** [comment] 2015-12-15 18:50
More docs on processing file uploads in the perldoc: https://metacpan.org/pod/distribution/CGI/lib/CGI.pod#Processing-a-file-upload-field

**Comment by ekangas1** [comment] 2015-12-15 22:28
Thank you for the link.
